# Дисциплина "Искусственный интеллект"

# Рабочая тетрадь № 2

# 1.1. Теоретический материал - Библиотека NumPy

NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.

Если у вас уже есть Python, вы можете установить NumPy с помощью
командной строки:
- pip install numpy

Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:
- import numpy as np

Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.

Наиболее важные атрибуты объектов ndarray:
- **ndarray.ndim** - число измерений (чаще их называют "оси") массива.
- **ndarray.shape** - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
- **ndarray.size** - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
- **ndarray.dtype** - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
- **ndarray.itemsize** - размер каждого элемента массива в байтах.
- **ndarray.data** - буфер, содержащий фактические элементы массива.
Обычно не нужно использовать этот атрибут, так как обращаться к
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html

# 1.2.1 Пример

## Задача:

Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

## Решение:

In [79]:
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print("Значения всего массива:")
print(x)
print("Значение элемента с индексом (3,1):")
print(x[3][1])
print("Значения второго столбца:")
print(x[1])

Значения всего массива:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Значение элемента с индексом (3,1):
8
Значения второго столбца:
[3 4]


# 1.2.2 Пример

## Задача:

Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный
нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.

## Решение:

In [80]:
import numpy as np

a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print("Вектор размера 10, заполненный нулями:")
print(a)
print("Вектор размера 10, заполненный единицами:")
print(b)
print("Вектор размера 10, заполненный заданным числом (5):")
print(c)
print("Вектор со значениями от 10 до 19:")
print(d)

Вектор размера 10, заполненный нулями:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Вектор размера 10, заполненный единицами:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Вектор размера 10, заполненный заданным числом (5):
[5 5 5 5 5 5 5 5 5 5]
Вектор со значениями от 10 до 19:
[10 11 12 13 14 15 16 17 18 19]


# 1.2.3 Пример

## Задача:

Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение.

## Решение:

In [91]:
import numpy as np

Z = np.random.random((10,10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print("Минимум из массива:")
print("{:.3f}".format(Zmin))
print("Максимум из массива:")
print("{:.3f}".format(Zmax))
print("Среднее значение из массива:")
print("{:.3f}".format(Zmean))

Минимум из массива:
0.003
Максимум из массива:
0.971
Среднее значение из массива:
0.415


# 1.2.4 Пример

## Задача:

Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами.

## Решение:

In [92]:
import numpy as np

A = np.arange(25).reshape(5,5)
print("Матрица до обмена 2 строк местами:")
print(A)
A[[0, 1]] = A[[1, 0]]
print("Матрица после обмена 2 строк местами:")
print(A)

Матрица до обмена 2 строк местами:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица после обмена 2 строк местами:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 1.2.5 Пример

## Задача:

Выяснить результат следующих выражений:

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1

## Решение:

In [93]:
import numpy as np

print("Результат выражения 0 * np.nan:")
print(0 * np.nan)
print("Результат выражения np.nan == np.nan:")
print(np.nan == np.nan)
print("Результат выражения np.inf > np.nan:")
print(np.inf > np.nan)
print("Результат выражения np.nan - np.nan:")
print(np.nan - np.nan)
print("Результат выражения 0.3 == 3 * 0.1:")
print(0.3 == 3 * 0.1)

Результат выражения 0 * np.nan:
nan
Результат выражения np.nan == np.nan:
False
Результат выражения np.inf > np.nan:
False
Результат выражения np.nan - np.nan:
nan
Результат выражения 0.3 == 3 * 0.1:
False


# 1.2.6 Пример

## Задача:

Отсортировать массив

## Решение:

In [94]:
import numpy as np

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print("Отсортированный массив:")
print(np.sort(arr))

Отсортированный массив:
[1 2 3 4 5 6 7 8]


# 1.3.1 Задание

## Задача:

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

## Решение:

In [96]:
import numpy as np

matrix = np.zeros((8, 8))
matrix[0::2, 1::2] = 1
matrix[1::2, 0::2] = 1
print("Матрица 8x8, заполненная в шахматном порядке нулями и единицами:")
print(matrix)

Матрица 8x8, заполненная в шахматном порядке нулями и единицами:
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 1.3.2 Задание

## Задача:

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

## Решение:

In [97]:
import numpy as np

matrix = np.zeros((5,5)) + np.arange(5)
print("Матрица 5x5 со значениями в строках от 0 до 4:")
print(matrix)

Матрица 5x5 со значениями в строках от 0 до 4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 1.3.3 Задание

## Задача:

Создать массив 3x3x3 со случайными значениями

## Решение:

In [8]:
import numpy as np

arr = np.around(np.random.rand(3, 3, 3), decimals=3)
print("Массив 3x3x3 со случайными значениями:")
print(arr)

Массив 3x3x3 со случайными значениями:
[[[0.125 0.577 0.884]
  [0.408 0.067 0.048]
  [0.782 0.506 0.551]]

 [[0.294 0.311 0.818]
  [0.201 0.83  0.757]
  [0.545 0.348 0.441]]

 [[0.801 0.535 0.513]
  [0.283 0.215 0.424]
  [0.571 0.86  0.375]]]


# 1.3.4 Задание

## Задача:

Создать матрицу с 0 внутри, и 1 на границах

## Решение:

In [105]:
import numpy as np

matrix = np.ones((9, 9))
matrix[1:-1, 1:-1] = 0
print("Матрица с 0 внутри, и 1 на границах:")
print(matrix)

Матрица с 0 внутри, и 1 на границах:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 1.3.5 Задание

## Задача:

Создайте массив и отсортируйте его по убыванию.

## Решение:

In [106]:
import numpy as np

arr = np.random.randint(0, 100, 10)
arr_sorted = np.sort(arr)[::-1]
print("Массив до сортировки по убыванию:")
print(arr)
print("Массив после сортировки по убыванию:")
print(arr_sorted)

Массив до сортировки по убыванию:
[87 98 57 14 67 83 76 95 56 65]
Массив после сортировки по убыванию:
[98 95 87 83 76 67 65 57 56 14]


# 1.3.6 Задание

## Задача:

Создайте матрицу, выведите ее форму, размер и размерность.

In [9]:
import numpy as np

matrix = np.zeros((9, 10)) 
print("Форма матрицы:")
print(matrix.shape)
print("Размер матрицы:")
print(matrix.size)
print("Размерность матрицы:")
print(matrix.ndim)

Форма матрицы:
(9, 10)
Размер матрицы:
90
Размерность матрицы:
2


# 2.1. Теоретический материал - Библиотека Pandas

Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких источников.

Библиотека pandas – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то pandas – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.

Библиотека pandas присутствует в стандартной поставке Anaconda. Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:

pip install pandas

Для импорта библиотеки используйте команду:

import pandas as pd

Библиотека pandas предоставляет две ключевые структуры данных: Series и DataFrame.

Series – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.

DataFrame – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

# 2.2.1 Пример

## Задача:

Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

## Решение:

In [17]:
import numpy as np
import pandas as pd

lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print("Series из списка:")
print(s1)
print("Series из словаря:")
print(s2)
print("Series из массива Numpy с установленными буквенными метками:")
print(s3)

Series из списка:
0    1
1    2
2    3
3    4
4    5
dtype: int64
Series из словаря:
a    1
b    2
c    3
dtype: int64
Series из массива Numpy с установленными буквенными метками:
a    1
b    2
c    3
d    4
e    5
dtype: int32


# 2.2.2 Пример

## Задача:

Дано два Series. Напечатать их первые элементы и все элементы после третьего (во втором фрейме).

## Решение:

In [19]:
import pandas as pd

s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print("Первый элемент первого Series:")
print(s1['a'])
print("Первый элемент второго Series:")
print(s2[0])
print("Все элементы после третьего из второго Series:")
print(s2[3:])

Первый элемент первого Series:
1
Первый элемент второго Series:
5
Все элементы после третьего из второго Series:
3    2
4    1
dtype: int64


# 2.2.3 Пример

## Задача:

Создайте новый фрейм данных

## Решение:

In [26]:
import pandas as pd

dataframe1 = pd.DataFrame()
dataframe1['Имя'] = ['Джеки Джексон', 'Стивен Стивенсон']
dataframe1['Возраст'] = [38, 25]
dataframe1['Водитель'] = [True, False]
print("Вывод фрейма данных:")
dataframe1

Вывод фрейма данных:


Имя  Возраст  Водитель
0     Джеки Джексон       38      True
1  Стивен Стивенсон       25     False

# 2.2.4 Пример

## Задача:

Загрузите фрейм данных по ссылке: https://raw.githubusercontent.com/chrisalbonsimulated_datasets/master/titanic.csv

## Решение:

In [99]:
import pandas as pd

# Создать URL-адрес
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
# Загрузить данные
dataframe = pd.read_csv(url)
# Показать пять строк
print("Вывод 5 строк фрейма данных:")
dataframe.head(5)

Вывод 5 строк фрейма данных:


Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

# 2.2.5 Пример

## Задача:

Пронализировать характеристики фрейма данных.

## Решение:

In [100]:
print("Первые 2 строки фрейма:")
dataframe.head(2)

Первые 2 строки фрейма:


Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [101]:
print("Последние 3 строки фрейма:")
dataframe.tail(3)

Последние 3 строки фрейма:


Name PClass   Age   Sex  Survived  SexCode
1310  Zenni, Mr Philip    3rd  22.0  male         0        0
1311  Lievens, Mr Rene    3rd  24.0  male         0        0
1312    Zimmerman, Leo    3rd  29.0  male         0        0

In [102]:
print("Количество строк и столбцов фрейма:")
dataframe.shape

Количество строк и столбцов фрейма:


(1313, 6)

In [103]:
print("Описательная статистика фрейма:")
dataframe.describe()

Описательная статистика фрейма:


Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

# 2.2.6 Пример

## Задача:

Выберите индивидуальные данные или срезы фрейма данных.

## Решение:

In [104]:
print("Элементы с 1 по 3 во фрейме:")
dataframe.iloc[1:4]

Элементы с 1 по 3 во фрейме:


Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

# 2.2.7 Пример

## Задача:

Требуется отобрать строки фрейма данных на основе некоторого условия. Необходимо сформировать новый фрейм данных из пассажиров первого класса.

## Решение:

In [106]:
print("2 элемента фрейма, имеющие 1 класс:")
dataframe[dataframe['PClass'] == '1st'].head(2)

2 элемента фрейма, имеющие 1 класс:


Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

# 2.3.1 Задание

## Задача:

Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

## Решение:

In [83]:
import pandas as pd

point_1 = pd.Series([1, 2, 3])
point_2 = pd.Series([4, 5, 6])

print("Евклидово расстояние между двумя Series точками:")
print((sum((point_1-point_2)**2))**(1/2))

Евклидово расстояние между двумя Series точками:
5.196152422706632


# 2.3.2 Задание

## Задача:

Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

## Решение:

In [89]:
import pandas as pd

url2 = "https://raw.githubusercontent.com/akmand/datasets/main/california_housing.csv"
dataframe2 = pd.read_csv(url2)
print("Вывод 10 строк фрейма данных:")
dataframe2.head(10)

Вывод 10 строк фрейма данных:


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   
5    -122.25     37.85                  52          919           213.0   
6    -122.25     37.84                  52         2535           489.0   
7    -122.25     37.84                  52         3104           687.0   
8    -122.26     37.84                  42         2555           665.0   
9    -122.25     37.84                  52         3549           707.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300  
4         565         259         3.8462        NEAR BAY              342200  
5         413         193         4.0368        NEAR BAY              269700  
6        1094         514         3.6591        NEAR BAY              299200  
7        1157         647         3.1200        NEAR BAY              241400  
8        1206         595         2.0804        NEAR BAY              226700  
9        1551         714         3.6912        NEAR BAY              261100

# 2.3.3 Задание

## Задача:

Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

## Решение:

In [90]:
import pandas as pd

url2 = 'https://raw.githubusercontent.com/akmand/datasets/main/california_housing.csv'

dataframe2 = pd.read_csv(url2)

print("Первые 5 строк фрейма:")
dataframe2.head(5)

Первые 5 строк фрейма:


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                  41          880           129.0   
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   
4    -122.25     37.85                  52         1627           280.0   

   population  households  median_income ocean_proximity  median_house_value  
0         322         126         8.3252        NEAR BAY              452600  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300  
4         565         259         3.8462        NEAR BAY              342200

In [91]:
print("Последние 3 строки фрейма:")
dataframe2.tail(3)

Последние 3 строки фрейма:


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
20637    -121.22     39.43                  17         2254           485.0   
20638    -121.32     39.43                  18         1860           409.0   
20639    -121.24     39.37                  16         2785           616.0   

       population  households  median_income ocean_proximity  \
20637        1007         433         1.7000          INLAND   
20638         741         349         1.8672          INLAND   
20639        1387         530         2.3886          INLAND   

       median_house_value  
20637               92300  
20638               84700  
20639               89400

In [92]:
print("Количество строк и столбцом фрейма:")
dataframe2.shape

Количество строк и столбцом фрейма:


(20640, 10)

In [93]:
print("Описательная статистика фрейма:")
dataframe2.describe()

Описательная статистика фрейма:


longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [94]:
print("Элементы с 1 по 3 во фрейме:")
dataframe2.iloc[1:4]

Элементы с 1 по 3 во фрейме:


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
1    -122.22     37.86                  21         7099          1106.0   
2    -122.24     37.85                  52         1467           190.0   
3    -122.25     37.85                  52         1274           235.0   

   population  households  median_income ocean_proximity  median_house_value  
1        2401        1138         8.3014        NEAR BAY              358500  
2         496         177         7.2574        NEAR BAY              352100  
3         558         219         5.6431        NEAR BAY              341300

In [111]:
print("5 элементов фрейма, имеющие total_rooms меньше 1000:")
dataframe2[dataframe2['total_rooms'] < 1000].head(5)

5 элементов фрейма, имеющие total_rooms меньше 1000:


longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0     -122.23     37.88                  41          880           129.0   
5     -122.25     37.85                  52          919           213.0   
13    -122.26     37.84                  52          696           191.0   
20    -122.27     37.85                  40          751           184.0   
25    -122.28     37.85                  41          535           123.0   

    population  households  median_income ocean_proximity  median_house_value  
0          322         126         8.3252        NEAR BAY              452600  
5          413         193         4.0368        NEAR BAY              269700  
13         345         174         2.6736        NEAR BAY              191300  
20         409         166         1.3578        NEAR BAY              147500  
25         317         119         2.4038        NEAR BAY              107500

# 3.1. Теоретический материал - Работа с числовыми данными

Количественные данные что-то измеряют – будь то размер класса, ежемесячные продажи или оценки учащихся. Естественным способом представления этих величин является численным (например, 150 студентов, $529 392 продаж).

**Нормализация данных** — это общепринятая задача предобработки в машинном обучении. Многие алгоритмы предполагают, что все признаки находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1.

Существует множество способов нормализации значений признаков, чтобы масштабировать их к единому диапазону и использовать в различных моделях машинного обучения. В зависимости от используемой функции, их можно разделить на 2 большие группы: линейные и нелинейные. При нелинейной нормализации в расчетных соотношениях используются функции логистической сигмоиды или гиперболического тангенса. В линейной нормализации изменение переменных осуществляется пропорционально, по линейному закону.

На практике наиболее распространены следующие методы нормализации признаков:

- **Минимакс** – линейное преобразование данных в диапазоне [0..1], где минимальное и максимальное масштабируемые значения соответствуют 0 и 1 соответственно;
- **Z-масштабирование** данных на основе среднего значения и стандартного отклонения: производят деление разницы между переменной и средним значением на стандартное отклонение.

Нормализация по методу минмакс:

$$ X_{norm} = \frac{X-X_{min}}{X_{max} - X_{min}} $$

Z-масштабирование:

$$ z = \frac{x - μ}{σ} $$

При масштабировании данных мы будем использовать одну из популярных библиотек машинного обучения Scikit-learn. Библиотека содержит пакет sklearn.preprocessing, который предоставляет широкие возможности для нормализации данных. Следует отметить, что в целом алгоритмы обучения выигрывают от стандартизации набора данных.

# 3.2.1. Пример

## Задача:

Прошкалируйте числовой признак в диапазоне между двумя значениями.

## Решение:

In [114]:
# Загрузить библиотеки
import numpy as np
from sklearn import preprocessing

# Создать признак
feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
# Создать шкалировщик
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))

# Прошкалировать признак
scaled_feature = minmax_scale.fit_transform(feature)

# Показать прошкалированный признак
print("Прошкалированный признак в диапазоне между двумя значениями:")
scaled_feature

Прошкалированный признак в диапазоне между двумя значениями:


array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# 3.2.2. Пример

## Задача:

Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное отклонение 1.

## Решение:

In [ ]:
import numpy as np
from sklearn import preprocessing

x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
# Создать шкалировщик
scaler = preprocessing.StandardScaler()
# Преобразовать признак
standardized = scaler.fit_transform(x)
# Показать признак
print("Признак:")
standardized

In [21]:
print("Среднее:", round(standardized.mean()))
print("Стандартное отклонение:", standardized.std())

Среднее: 0
Стандартное отклонение: 1.0


# 3.2.3. Пример

## Задача:

Дан фрейм данных

dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
 
 Необходимо масштабировать его числовые столбцы.

## Решение:

In [121]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})

dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
print("Промасштабированный фрейм:")
dfTest

Промасштабированный фрейм:


A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

# 3.3.2. Задание

## Задача:

Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.

Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

## Решение:

In [124]:
import pandas as pd
from sklearn import preprocessing

url3 = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'

dataframe3 = pd.read_csv(url3)

minmax_scaler = preprocessing.MinMaxScaler()
z_scaler = preprocessing.StandardScaler()

dataframe3[['sepal_length_cm']] = minmax_scaler.fit_transform(dataframe3[['sepal_length_cm']])
dataframe3[['sepal_width_cm']] = z_scaler.fit_transform(dataframe3[['sepal_width_cm']])

print("Фрейм с нормализованными первым и вторым числами:")
dataframe3

Фрейм с нормализованными первым и вторым числами:


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]